#!/bin/sh
#$ -N emergingtransformer9
#$ -cwd
#$ -q cuda.q
#$ -S /bin/bash
#$ -M lukas.galke@mpi.nl
#$ -m beas

set -e
#conda deactivate  # make sure we're not in base environ
module load "miniconda/3.2021.10"  # load miniconda module
conda activate pytorch  # activate pytorch conda environment
python3 main.py --max_len 6 --distractors_num -1 --num_workers 1 --log_interval 5 --n_epochs 10000 --batch_size 8
