#!/bin/sh
#$ -N emergingtransformer9
#$ -cwd
#$ -q cuda.q
#$ -S /bin/bash
#$ -M lukas.galke@mpi.nl
#$ -m beas

set -e
#conda deactivate  # make sure we're not in base environ
module load "miniconda/3.2021.10"  # load miniconda module
conda activate pytorch  # activate pytorch conda environment
python3 src/main.py --max_len 6 --distractors_num 0 --num_workers 1 --log_interval 100 --n_epochs 1000 --batch_size 64 --update_freq 1 --data_split 0.1
