wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1708700644.927595
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      3:
      - 1
      - 23
      4: 3.9.6
      5: 0.16.2
      6: 4.36.2
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
weight_decay:
  desc: null
  value: 1.0e-05
use_larc:
  desc: null
  value: false
pdb:
  desc: null
  value: false
dataset_dir:
  desc: null
  value: ./data
dataset_name:
  desc: null
  value: imagenet
distractors_num:
  desc: null
  value: 0
num_workers:
  desc: null
  value: 1
return_original_image:
  desc: null
  value: false
gs_temperature:
  desc: null
  value: 1.0
gs_temperature_decay:
  desc: null
  value: 1.0
train_gs_temperature:
  desc: null
  value: false
straight_through:
  desc: null
  value: false
update_gs_temp_frequency:
  desc: null
  value: 1
minimum_gs_temperature:
  desc: null
  value: 1.0
model_name:
  desc: null
  value: resnet50
vision_chk:
  desc: null
  value: google/vit-base-patch16-224-in21k
shared_vision:
  desc: null
  value: false
pretrain_vision:
  desc: null
  value: false
use_augmentations:
  desc: null
  value: false
loss_type:
  desc: null
  value: xent
loss_temperature:
  desc: null
  value: 0.1
similarity:
  desc: null
  value: cosine
use_distributed_negatives:
  desc: null
  value: false
projection_hidden_dim:
  desc: null
  value: 2048
projection_output_dim:
  desc: null
  value: 2048
simclr_sender:
  desc: null
  value: false
discrete_evaluation_simclr:
  desc: null
  value: false
random_seed:
  desc: null
  value: 1639317329
checkpoint_dir:
  desc: null
  value: null
preemptable:
  desc: null
  value: false
checkpoint_freq:
  desc: null
  value: 0
validation_freq:
  desc: null
  value: 1
n_epochs:
  desc: null
  value: 100
load_from_checkpoint:
  desc: null
  value: null
no_cuda:
  desc: null
  value: true
batch_size:
  desc: null
  value: 32
optimizer:
  desc: null
  value: adam
lr:
  desc: null
  value: 0.01
update_freq:
  desc: null
  value: 1
vocab_size:
  desc: null
  value: 10
max_len:
  desc: null
  value: 1
tensorboard:
  desc: null
  value: false
tensorboard_dir:
  desc: null
  value: runs/
distributed_port:
  desc: null
  value: 18363
fp16:
  desc: null
  value: false
cuda:
  desc: null
  value: false
device:
  desc: null
  value: cpu
distributed_context:
  desc: null
  value:
    is_distributed: false
    rank: 0
    local_rank: 0
    world_size: 1
    mode: none
